version: '3.8'

services:

  nginx:
    build:
      context: ./.docker
      dockerfile: nginx.dockerfile
      args:
        - DOCKERCOMPOSE_USERID=${DOCKERCOMPOSE_USERID:-1000}
        - DOCKERCOMPOSE_GROUPID=${DOCKERCOMPOSE_GROUPID:-1000}
    ports:
      - '${DOCKERCOMPOSE_WEB_PORT:-8099}:80'
    volumes:
      - .:/var/www/html:delegated
    depends_on:
      - php
      - mysql
    networks:
      - thenetwork

  mysql:
    platform: linux/amd64
    image: mysql:5.7
    command: --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: 'thedockeruser'
      MYSQL_PASSWORD: 'thepassword'
      MYSQL_ROOT_PASSWORD: 'therootpassword'
      MYSQL_DATABASE: 'thedatabase'
    ports:
      - '${DOCKERCOMPOSE_DB_PORT:-3309}:3306'
    volumes:
      - thedbvolume:/var/lib/mysql
    networks:
      - thenetwork

  php:
    build:
      context: ./.docker
      dockerfile: php.dockerfile
      args:
        - DOCKERCOMPOSE_USERID=${DOCKERCOMPOSE_USERID:-1000}
        - DOCKERCOMPOSE_GROUPID=${DOCKERCOMPOSE_GROUPID:-1000}
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html:delegated
    networks:
      - thenetwork

volumes:
  thedbvolume:
    driver: local

networks:
  thenetwork:
    driver: bridge
